dags:
  process_init:
    spark:
      master: spark://spark-master:7077
      total-executor-cores: 1
      executor-memory: 512M
      jars: $(echo /opt/airflow/jars/*.jar | tr ' ' ',')
      script: /opt/spark-apps/silver/silver_ingestion.py init
  process_match:
    spark:
      master: spark://spark-master:7077
      total-executor-cores: 1
      executor-memory: 512M
      jars: $(echo /opt/airflow/jars/*.jar | tr ' ' ',')
      script: /opt/spark-apps/silver/silver_ingestion.py match
  process_in-app-purchase:
    spark:
      master: spark://spark-master:7077
      total-executor-cores: 1
      executor-memory: 512M
      jars: $(echo /opt/airflow/jars/*.jar | tr ' ' ',')
      script: /opt/spark-apps/silver/silver_ingestion.py in-app-purchase