spark:
  submit_bronze:
    master: spark://spark-master:7077
    total-executor-cores: 1
    executor-memory: 512M
    jars: $(echo /opt/airflow/jars/*.jar | tr ' ' ',')
    script: /opt/spark-apps/bronze/bronze_extraction.py
