/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package generator;

import com.fasterxml.jackson.databind.ObjectMapper;
import structures.InitEvent;

import java.io.File;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());
    }
}
