/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package generator;

import com.fasterxml.jackson.databind.ObjectMapper;
import eventgenerator.EventGeneratorImpl;
import kafka.Producer;
import structures.InitEvent;

public class App {
    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());
        EventGeneratorImpl eventGenerator = new EventGeneratorImpl();
        InitEvent initEvent = eventGenerator.generateInitEvent("2023-06-01");
        ObjectMapper mapper = new ObjectMapper();
        String initEventString = mapper.writeValueAsString(initEvent);
        System.out.println(initEventString);
        new Producer().runAlways("magic-topic");
    }

    public String getGreeting() {
        return "Hello World!";
    }
}
